spring.application.name=vacancy-parser
spring.datasource.url=jdbc:h2:mem:vacanciesdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Показывать SQL с параметрами
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Показывать SQL-запросы
logging.level.org.hibernate.SQL=DEBUG

# Показывать параметры в запросах (для Hibernate 6+)
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# Actuator / Micrometer / Prometheus
management.endpoints.web.exposure.include=health,info,metrics,threaddump,prometheus
management.endpoint.health.show-details=always
management.metrics.export.prometheus.enabled=true
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.metrics.distribution.percentiles.http.server.requests=0.5,0.95,0.99
